<div id="myDialog" style="display:none;">
    <div class="dialogtitle clearfix">
        <h3 class="fl title"></h3>
        <a class="modal_close fr close" id="mymodal_close" href="javascript:void(0);">关闭</a>
    </div>
    <div class="dialogInner">
        <h4 class="content"></h4>
        <div class="btn_area">
            <input type="button" class="ok" value="确定" id="mymodal_ok" />
            <input type="button" class="close" value="取消" id="mymodal_close2" />
        </div>
    </div>
</div>